---
title: "Lists"
date: "2025-07-11"
filters:
    - social-share
share:
    permalink: "https://tylerhillery.com/list"
    description: List of things 
    twitter: true
    facebook: false
    reddit: true
    stumble: false
    tumblr: false
    linkedin: true
    email: true
    mastodon: true
---

*The lists are in no particular order*

# My Content 
::: {.callout-note appearance="minimal" collapse=true title="️Videos 📺"} 
- [Supabase Storage and DuckDB Demo](https://github.com/TylerHillery/supabase-storage-duckdb-demo)
:::

::: {.callout-note appearance="minimal" collapse=true title="Talks 🗣️"} 
- [Supabase Community Meetup - Solving Practical Problems with Window Functions & Range Joins (Slides)](https://onedrive.live.com/:p:/g/personal/B108287C54AF8760/s!AmCHr1R8KAix30k1LypT60PBnd-P?resid=B108287C54AF8760!12233&ithint=file%2Cpptx&e=KrLEva&migratedtospo=true&redeem=aHR0cHM6Ly8xZHJ2Lm1zL3AvcyFBbUNIcjFSOEtBaXgzMGsxTHlwVDYwUEJuZC1QP2U9S3JMRXZh)
:::

# Favorites

::: {.callout-note appearance="minimal" collapse=true title="Talks 🗣️"} 
- [The Summer of Rust](https://youtu.be/YKv_IDN0zCA?si=NfIPPYvK5PPfM9V3)
- [Bryan Cantrill on Jails and Solaris Zones](https://youtu.be/hgN8pCMLI2U?si=V8LFUTtzLSl3jfcx)
- [Is It Time to Rewrite the Operating System in Rust? by Bryan Cantrill](https://www.infoq.com/presentations/os-rust/)
- [A Wardrobe for the Emperor: Stitching practical bias into systems software research by Bryan Cantrill](https://www.youtube.com/watch?v=gAEiXWO44bQ)
- [Debugging Under Fire: Keep your Head when Systems have Lost their Mind • Bryan Cantrill • GOTO 2017](https://www.youtube.com/watch?v=30jNsCVLpAE)
- [Monktoberfest 2016: Bryan Cantrill - Oral Tradition in Software Engineering](https://www.youtube.com/watch?v=4PaWFYm0kEw&t=2s)
- [Social Audio as a Vector For Engineering Wisdom by Bryan Cantrill](https://www.youtube.com/watch?v=W8qiDhlFVCE)
- [Platform as a Reflection of Values by Bryan Cantrill](https://www.youtube.com/watch?v=Xhx970_JKX4)
- [Let's all write good software by Will Wilson](https://youtu.be/eZ1mmqlq-mY?si=RO6wJJObSOKRVDze)
- [Intelligence is not Enough by Bryan Cantrill](https://www.youtube.com/watch?v=bQfJi7rjuEk)
- [Coming Of Age by Bryan Cantrill](https://www.youtube.com/watch?v=VzdVSMRu16g)
- [Instrumenting the real-time web: Node.js, DTrace and the Robinson Projection by Bryan Cantrill](https://www.youtube.com/watch?v=_jS_XkCkpVI)
- [Leaping the chasm from proprietary to open: A survivor's guide by Bryan Cantrill](https://youtu.be/Zpnncakrelk?si=C6WwyFvbIoykN6R0)
- [Surge 2013: Leadership Without Management: Scaling Organizations by Scaling Engineers by Bryan Cantrill](https://youtu.be/1KeYzjILqDo?si=ioK4UqA9k4JG_OIJ) 
- [Surge 2013: LightningTalks by Bryan Cantrill](https://www.youtube.com/watch?v=vm1GJMp0QN4)
- [The Container Revolution: Reflections After the First Decade by Bryan Cantrill](https://www.youtube.com/watch?v=xXWaECk9XqM&t=1287s)
- [Run containers on bare metal already! by Bryan Cantrill](https://youtu.be/coFIEH3vXPw?si=swTZO931l24k-RIB)
- [LISA11 - Fork Yeah! The Rise and Development of illumos by Bryan Cantrill](https://youtu.be/-zRN7XLCRhc?si=etALDphQTOFxBane)
- [Running Aground: Debugging Docker in Production by Bryan Cantrill](https://youtu.be/AdMqCUhvRz8?si=yxMuuRGXXbK6a_t3)
- [The Hurricane's Butterfly: Debugging Pathologically Performing Systems by Bryan Cantrill](https://www.youtube.com/watch?v=7AO4wz6gI3Q&list=WL&index=2)
- [Principles of Technology Leadership by Bryan Cantrill](https://youtube.com/watch?v=9QMGAtxUlAc&si=OCf_ZuuA0t6uyJ7t)
- [Bringing the Unix Philosophy to Big Data by Bryan Cantrill](https://youtube.com/watch?v=S0mviKhVmBI&si=YUtVlmPfneUaOR2g)
- [Rust and Other Interesting Things by Bryan Cantrill](https://youtube.com/watch?v=2wZ1pCpJUIM&si=qQ5hIenYVQGtLP_A)
- [Zebras All the Way Down by Bryan Cantrill](https://www.youtube.com/watch?v=fE2KDzZaxvE)
- [It Was Never Going to Work, So Let’s Have Some Tea (with Q&A) by James Mickens](https://www.youtube.com/watch?v=J4QlTYJSS_w)
- [Advanced Napkin Math: Estimating System Performance from First Principles by Simon Eskildsen](https://youtu.be/IxkSlnrRFqc?si=Lgj9HoYQWyoC3Bhj)
- [Making Badass Developers by Kathy Sierra](https://youtu.be/FKTxC9pl-WM?si=BkTzk7j0EnnyLECu)
- [Simple Made Easy by Rich Hickey](https://youtu.be/SxdOUGdseq4?si=fZZqec-D5eu9SSw0)
- [Wat by Gary Bernhardt](https://www.destroyallsoftware.com/talks/wat)
- [A Short Summary of the Last Decades of Data Management by Hannes Mühleisen](https://youtu.be/-wCzn9gKoUk?si=IjrTQN2PfLi5v6W7)
- [Gang of None? Design Patterns in Elixir by José Valim](https://youtu.be/agkXUp0hCW8?si=ZZxErACww18LDyrd)
- [The past, present, and future of local-first by Martin Kleppmann](https://youtu.be/NMq0vncHJvU?si=MltJeAPhmx1eSXCq)
- [Stop Writing Classes by Jack Diederich](https://youtu.be/o9pEzgHorH0?si=Nn5B6p1mLFgCKwid)
- [Performance Matters by Emery Berger](https://youtu.be/r-TLSBdHe1A?si=KIF7Jlnct2EL-QIm)
- [Moving 17 years of old legacy code and sites into the Cloud by Scott Hanselman](https://youtu.be/mE-DGW0CcAk?si=mPi0CwhGj_OV-yAz)
- [Don't Do Invisible Work by Chris Albon](https://youtu.be/HiF83i1OLOM?si=kJgYoeAv5ZkRcwif)
- [Excel at nothing: How to be an effective generalist by Stephen Bailey](https://www.youtube.com/live/wB0ulHmvU7E?si=cEj5c6dISiwhxKlu)
- [How to Play Well With Others by Josh Wills](https://youtu.be/rqWnEJXnfiY?si=6kdMFqyBRBjPM1h1)
- [Computers are a Sadness, I am the Cure by James Mickens](https://youtu.be/3-GpiKQr9Rs?si=vLUSUV_cSudHYdz7)
- [Rails World 2024 Opening Keynote by David Heinemeier Hansson](https://youtu.be/-cEn_83zRFw?si=hRaEA_VmZcmiXg55)
- [Redesigning OLTP for a New Order of Magnitude by Joran Dirk Greef](https://youtu.be/32LMicc0gRA?si=vzHKNuHv4exe3dN6)
- [Nothing is Something by Sandi Metz](https://youtu.be/OMPfEXIlTVE?si=GglvzBuNGLLQ9g5G)
:::

::: {.callout-note appearance="minimal" collapse=true title="Podcasts Episodes🎙️"} 
- [RIP USENIX ATC - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/rip-usenix-atc)
- [Solutions Software Engineering with Matthew Sanabria - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/solutions-software-engineering-with-matthew-sanabria)
- [Bringing up Cosmo - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/bringing-up-cosmo)
- [Hell is other networks - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/hell-is-other-networks)
- [Raiding the Minibar - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/raiding-the-minibar)
- [Lip-Bu Tan's Intel - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/lip-bu-tans-intel)
- [A Half-Century of Silicon Valley with Randy Shoup - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/a-half-century-of-silicon-valley-with-randy-shoup/transcript)
- [Holistic Engineering with Robert Mustacchi - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/holistic-engineering-with-robert-mustacchi)
- [Crates We Love - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/crates-we-love/transcript)
- [OxF 2024 Wrap-Up - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/oxf-2024-wrap-up)
- [Querying Metrics with OxQL - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/querying-metrics-with-oxql)
- [RTO or GTFO - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes?page=2&per=20)
- [Reflecting on Founder Mode - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/reflecting-on-founder-mode)
- [RFDs: The Backbone of Oxide - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/rfds-the-backbone-of-oxide)
- [Whither CockroachDB? - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/whither-cockroachdb)
- [The Saga of Sagas - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/the-saga-of-sagas)
- [CrowdStrike BSOD Fiasco with Katie Moussouris - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/crowdstrike-bsod-fiasco-with-katie-moussouris) 
- [Heterogeneous Computing with Raja Koduri - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/heterogeneous-computing-with-raja-koduri)
- [Is NVIDIA like Sun from the Dot Com Bubble? - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/is-nvidia-like-sun-from-the-dot-com-bubble)
- [Rebooting a datacenter: A decade later - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/rebooting-a-datacenter-a-decade-later)
- [Discovering the XZ Backdoor with Andres Freund - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/discovering-the-xz-backdoor-with-andres-freund)
- [Cultural Idiosyncrasies - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/cultural-idiosyncrasies)
- [Data Visualization - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/data-visualization)
- [Crucible: The Oxide Storage Service - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/crucible-the-oxide-storage-service)
- [What's taking so long?! - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/whats-taking-so-long)
- [Framework Computer with Nirav Patel - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/framework-computer-with-nirav-patel)
- [Hiring Processes with Gergely Orosz - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/hiring-processes-with-gergely-orosz)
- [Launching the Cloud Computer - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/launching-the-cloud-computer)
- [Settling Beef - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/settling-beef)
- [Mr. Nagle's Wild Ride - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/mr-nagles-wild-ride)
- [Tales from Manufacturing: Shipping Rack - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/tales-from-manufacturing-shipping-rack-1)
- [Shipping the first Oxide rack: Your questions answered! - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/shipping-the-first-oxide-rack-your-questions-answered)
- [Breaking it down with Ian Brown - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/breaking-it-down-with-ian-brown)
- [Holistic Boot - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/holistic-boot)
- [Bringup Lab Chronicles: A Measurement Two Years in the Making - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/bringup-lab-chronicles-a-measurement-two-years-in-the-making)
- [Surviving Conventional Wisdom - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/surviving-conventional-wisdom)
- [Across the Chasm with Rust - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/across-the-chasm-with-rust)
- [Books in the box redux - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/book-in-the-box-redux)
- [Paths into Systems Programming - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/paths-into-systems-programming?)
- [Surviving the Dot-Com Bust - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/surviving-the-dot-com-bust) 
- [Fail Whaling - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/fail-whaling)
- [More Tales from the Bringup Lab](https://oxide-and-friends.transistor.fm/episodes/more-tales-from-the-bringup-lab)
- [Time, Timezones, Metric Time, Losing and Saving - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/time-timezones-metric-time-losing-and-saving-2022-03-28)
- [Engineering Culture - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/engineering-culture-2022-02-21)
- [I know this! (Purpose-built systems with general-purpose guts) - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/i-know-this-purpose-built-systems-with-general-purpose-guts-2022-02-07)
- [Tales from the Bringup Lab - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/tales-from-the-bringup-lab-2021-12-06)
- [Supercomputers, Cray, and How Sun Picked SGI's Pocket - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/supercomputers-cray-and-how-sun-picked-sgis-pocket-2021-11-08)
- [Dijkstra's Tweetstorm - Oxide and Friends](https://oxide-and-friends.transistor.fm/episodes/dijkstras-tweetstorm-2021-10-18)
- [Amir Michael - On The Metal](https://onthemetal.transistor.fm/episodes/amir-michael)
- [How to Make Yourself Into a Learning Machine with Simon Eskildsen](https://every.to/superorganizers/how-to-build-a-learning-machine-299655?sid=16664)
- [How to Use AI to Become a Learning Machine - Ep. 34 with Simon Eskildsen](https://youtu.be/D_4AYLr_hFI?si=TbvtqSDpbtqwp36t)
- [DHH Is Right About Everything](https://youtu.be/mTa2d3OLXhg?si=eiJf3cnUc7MowxdV)
- [DHH Talks Apple, Linux and Running Servers](https://youtu.be/fEy9JhHk6lg?si=HR5nmrm9cB9rnhRm)
- [I Interviewed Chris Lattner, The Creator Of LLVM, Clang, Swift, and Mojo](https://youtu.be/ovYbgbrQ-v8?si=dTbQua9Dk2kKnXSa)
- [Swift creator Chris Lattner on Mojo & Roc](https://youtu.be/ENviIxDTmUA?si=QHDR_i4HM5Ro7eQn)
- [Managers should know how to code feat. Thorsten Ball](https://youtu.be/ruW9wtH2AZs?si=bRzCvqVQWLlcyXZg)
- [Do you love programming as much as Thorsten Ball does?](https://youtu.be/_JA04KfD7a4?si=Z3KruMOLKcjvEZAo)
- [Thorsten Ball, Software Engineer at Zed](https://youtu.be/KI1Q_rdfH0k?si=BIFEM8hWUXe1Z4Of)
- [Stories behind building HashiCorp | Mitchell Hashimoto](https://youtu.be/vMzToDQPgH4?si=RMVC2Vn75pV-RAnQ)
- [Mitchell Hashimoto - Founder of HashiCorp, Terraform, and Thoughts of Open Source Monetization](https://youtu.be/vw61iI08iro?si=RI5hoFrnhlmgXkG4)
- [The hard power of management and the soft power of senior ICs | Josh Wills](https://youtu.be/Pmnb5FsdfNs?si=eeZw9Twewo2Dp6M6)
- [Databases, Ambitions, and a Testing Silver Bullet? (With Joran Dirk Greef)](https://youtu.be/ayG7ltGRRHs?si=Bniz6V0m25LLJFP5)
- [Creator of Ghostty talks Zig over Go](https://youtu.be/YQnz7L6x068?si=73_6wfhzblymnV-c)
:::

::: {.callout-note appearance="minimal" collapse=true title="Books 📚"} 
- [Code: The Hidden Language of Computer Hardware and Software](https://www.tylerhillery.com/notes/code-hidden-language/)
- [Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones](https://www.tylerhillery.com/notes/atomic-habits/)
- [Designing Data-Intensive Applications](https://www.tylerhillery.com/notes/ddia/)
- [The Pragmatic Programmer](https://www.tylerhillery.com/notes/pragmatic-programmer/)
- [Effective Python](https://www.tylerhillery.com/notes/effective-python/)
- [A Philosophy of Software Design](https://www.tylerhillery.com/notes/philosophy-of-software-design/)
- [High Performance Browser Networking](https://hpbn.co/)
:::

::: {.callout-note appearance="minimal" collapse=true title="Blog Posts📝"} 
- [The Best Programmers I Know](https://endler.dev/2025/best-programmers)
- [The hunt for the Holy Grail by Benn Stancil](https://benn.substack.com/p/the-hunt-for-the-holy-grail?utm_source=pocket_shared)
- [Obsession by Phil Eaton](https://notes.eatonphil.com/2024-08-24-obsession.html)
- [Be someone who does things by Phil Eaton](https://notes.eatonphil.com/2024-09-23-be-someone-who-does-things.html)
- [Polishing Forks by Thorsten Ball](https://registerspill.thorstenball.com/p/polishing-forks)
- [The Grug Brained Developer](grugbrain.dev)
- [It's hard to write code for computers, but it's even harder to write code for humans by Erik Bernhardsson](https://erikbern.com/2024/09/27/its-hard-to-write-code-for-humans?s=09)
- [I don't want to learn your garbage query language by Erik Bernhardsson](https://erikbern.com/2018/08/30/i-dont-want-to-learn-your-garbage-query-language?)
- [Programmers should stop celebrating incompetence by DHH](https://world.hey.com/dhh/programmers-should-stop-celebrating-incompetence-de1a4725)
- [Teach Yourself Programming in Ten Years by Peter Norvig](https://norvig.com/21-days.html)
- [Being a High-Leverage Generalist](https://char.blog/generalist)
- [Professional Programming: The First 10 Years by Thorsten Ball](https://thorstenball.com/blog/2022/05/17/professional-programming-the-first-10-years/)
- [How can you not be romantic about programming? by Thorsten Ball](https://thorstenball.com/blog/2020/09/08/how-can-you-not-be-romantic-about-programming/)
:::

::: {.callout-note appearance="minimal" collapse=true title="Academic Papers 📄"} 
- [The Composable Data Management System Manifesto](https://www.vldb.org/pvldb/vol16/p2679-pedreira.pdf)
- [What Goes Around Comes Around... And Around... by Micheal Stonebraker and Andrew Pavlo](https://db.cs.cmu.edu/papers/2024/whatgoesaround-sigmodrec2024.pdf)
:::

::: {.callout-note appearance="minimal" collapse=true title="Conferences 👥"} 
- [Open Sauce](https://opensauce.com/)
- [ALL Things Open](https://allthingsopen.org/)
- [Open Source Summit](https://events.linuxfoundation.org/open-source-summit-north-america/)
- [Better Software Conf](https://bettersoftwareconference.com/)
- [FOSDEM](https://fosdem.org/2025/)
- [Cloud Native Con](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/)
- [Systems Distributed](https://systemsdistributed.com/)
- [P99 Conf](https://www.p99conf.io/)
- [SIGMOD](https://sigmod.org/)
- [VLDB](https://vldb.org/2024/)
- [CIDR](https://www.cidrdb.org/)
- [SRECON](https://www.usenix.org/conference/srecon)
- [QCon](https://qconferences.com/)
- [GoTo](https://gotopia.tech/)
- [LambdaConf](https://www.lambdaconf.us/)
- [PyCon US](https://us.pycon.org/)
- [GopherCon](https://www.gophercon.com/)
- [RustConf](https://rustconf.com/)
- [JSNation](https://jsnation.com/)
- [JSConf](https://events.linuxfoundation.org/jsconf-north-america/)
- [SquiggleConf](https://squiggleconf.com/)
- [Local First Conference](https://www.localfirstconf.com/)
- [Data Council](https://www.datacouncil.ai/)
- [DuckCon](https://duckdb.org/events/)
- [Current](https://current.confluent.io/)
:::

::: {.callout-note appearance="minimal" collapse=true title="Tweets 🐦"} 
{{< tweet karpathy 1756380066580455557 >}}
{{< tweet josh_wills 1508624385241849856 >}}
{{< tweet teej_m 1489491830580264960 >}}
:::

# Following 

::: {.callout-note appearance="minimal" collapse=true title="Newsletters & Blogs 📰"} 
- [Adam Leventhal's Personal Blog](https://ahl.dtrace.org/blog/)
- [Bryan Cantrill's Personal Blog](https://bcantrill.dtrace.org/)
- [Charity Majors' Personal Blog](https://charity.wtf/)
- [Register Spill by Thorsten Ball](https://registerspill.thorstenball.com/)
- [benn.substack by Benn Stancil](https://benn.substack.com)
- [Simon Willison's Weblog](https://simonwillison.net/)
- [Phil Eaton's Personal Blog](https://notes.eatonphil.com/)
- [Erik Bernhardsson's Personal Blog](https://erikbern.com/)
- [Vicki Boykis' Personal Blog](https://vickiboykis.com/)
- [Mitchell Hashimoto's Personal Blog](https://mitchellh.com/writing)
- [Gunnar Morling's Personal Blog](https://www.morling.dev/)
- [Jack Vanlightly's Personal Blog](https://jack-vanlightly.com/)
- [Hynek Schlawack's Personal Blog](https://hynek.me/articles/)
- [Anton Zhiyanov's Personal Blog](https://antonz.org/all/)
- [Fatih Arslan's Personal Blog](https://arslan.io/blog/)
- [Benjamin Dicken's Personal Blog](https://benjdd.com/work/)
- [Marc Brooker's Personal Blog](https://brooker.co.za/blog/)
- [Nanda Syahrasyad's Personal Blog](https://www.nan.fyi/)
- [Kit Langton's Personal Website](https://www.kitlangton.com/)
- [Brandur's Personal Blog](https://brandur.org/)
:::

::: {.callout-note appearance="minimal" collapse=true title="Podcasts 🎙️"} 
- [Developer Voices](https://www.youtube.com/@DeveloperVoices)
- [Software Huddle](https://www.youtube.com/@SoftwareHuddle)
- [Syntax](https://www.youtube.com/@syntaxfm)
- [How About Tomorrow?](https://www.youtube.com/@tomorrowfm)
- [Software Misadventures ](https://youtube.com/@softwaremisadventures)
- [devtools-fm](https://www.youtube.com/@devtoolsfm)
- [Acquired](https://www.acquired.fm/)
- [Lenny's Podcast](https://www.lennysnewsletter.com/podcast)
- [localfirst.fm](https://www.localfirst.fm/)
- [ADSP The Podcast](https://adspthepodcast.com/)
- [Happy Path Programming](https://podcasters.spotify.com/pod/show/happypathprogramming)
- [Software Unscripted](https://pod.link/1602572955)
- [Oxide and Friends](https://oxide.computer/podcasts/oxide-and-friends)
- [Software Engineering Daily](https://softwareengineeringdaily.com/category/all-episodes/exclusive-content/Podcast/)
:::

::: {.callout-note appearance="minimal" collapse=true title="YouTube Channels 📺"} 
- [CMU Database Group](https://www.youtube.com/@CMUDatabaseGroup)
- [Supabase](https://www.youtube.com/@Supabase)
- [Honeypot](https://www.youtube.com/@Honeypotio)
- [Hussein Nasser](https://www.youtube.com/@hnasr)
- [Fireship](https://www.youtube.com/@Fireship)
- [ThePrimeTime](https://www.youtube.com/@ThePrimeTimeagen/videos)
- [Code Report](https://www.youtube.com/@code_report)
- [Aaron Francis](https://www.youtube.com/@aarondfrancis)
- [TigerBeetle](https://www.youtube.com/@tigerbeetledb)
- [anthonywritescode](https://www.youtube.com/@anthonywritescode)
- [mCoding](https://www.youtube.com/@mCoding)
:::

::: {.callout-note appearance="minimal" collapse=true title="Discord 👾"} 
- [Software Internals](https://eatonphil.com/discord.html)
- [Local First Software](https://localfirstweb.dev/)
- [DuckDB](https://discord.duckdb.org/)
:::

# Tech I Find Interesting
*These are examples of the kinds of technologies I find interesting. The specific tools listed are less important, but illustrate the categories.*

::: {.callout-note appearance="minimal" collapse=true title="Languages 📜"} 
- [SQL](https://en.wikipedia.org/wiki/SQL)
- [Python](https://www.python.org/)
- [TypeScript](https://www.typescriptlang.org/)
- [Go](https://go.dev/)
- [Rust](https://www.rust-lang.org/)
- [Mojo](https://www.modular.com/mojo)
- [C](https://www.c-language.org/)
- [C++](https://isocpp.org/)
:::

::: {.callout-note appearance="minimal" collapse=true title="Databases 🗄️"} 
- OLTP
    - [PostgreSQL](https://www.postgresql.org/)
    - [SQLite](https://sqlite.org/)
    - [Vitess](https://vitess.io/)
    - [Convex](https://www.convex.dev/)
- OLAP 
    - [DuckDB](https://duckdb.org/)
    - [ClickHouse](https://github.com/ClickHouse/ClickHouse)
- Key Value
    - [Redis](https://github.com/redis/redis)
    - [Memcached](https://memcached.org/)
    - [DynamoDB](https://aws.amazon.com/dynamodb/)
- Time Series
    - [Prometheus](https://github.com/prometheus/prometheus)
    - [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics)
- Search & Vector Stores
    - [Elastic Search](https://github.com/elastic/elasticsearch)
    - [Lucene](https://github.com/apache/lucene)
    - [Tantivy](https://github.com/quickwit-oss/tantivy)
    - [Turbopuffer](https://turbopuffer.com/)
- Incremental View Maintenance / Sync Engines
    - [MaterializeDB](https://materialize.com/)
    - [Zero Sync](https://zero.rocicorp.dev/)
    - [Electric SQL](https://electric-sql.com/)
:::

::: {.callout-note appearance="minimal" collapse=true title="Messaging Systems ✉️"} 
- [Kafka](https://kafka.apache.org/)
- [NATS](https://nats.io/)
- [RabbitMQ](https://www.rabbitmq.com/)
:::

::: {.callout-note appearance="minimal" collapse=true title="Proxies/API Gateways/Networking 🌐"} 
- Proxies
    - [Caddy](https://caddyserver.com/)
    - [NGINX](https://nginx.org/)
    - [HAProxy](https://www.haproxy.org/)
    - [Traefik](https://traefik.io/)
    - [Envoy](https://www.envoyproxy.io/)
- API Gateways
    - [Kong](https://konghq.com/)
    - [Tyk](https://tyk.io/)
- Networking
    - [Pingora](https://github.com/cloudflare/pingora)
    - [Tailscale](https://tailscale.com/)
    - [ngrok](https://ngrok.com/)
:::

::: {.callout-note appearance="minimal" collapse=true title="️Durable Execution/Task Queues/Workflows ⚙️"} 
- Durable Execution
    - [Temporal](https://temporal.io/)
    - [Restate](https://restate.dev/)
    - [DBOS](https://dbos.dev/)
    - [Golem](https://golem.cloud/)
- Workflow Orchestration
    - [Airflow](https://airflow.apache.org/)
    - [Prefect](https://www.prefect.io/)
    - [Dagster](https://dagster.io/)
    - [Steno](https://github.com/oxidecomputer/steno)
- Task Queues
    - [Celery](https://docs.celeryq.dev/en/stable/)
    - [BullMQ](https://bullmq.io/)
    - [pg-boss](https://github.com/timgit/pg-boss)
    - [Inngest](https://www.inngest.com/)
    - [River](https://riverqueue.com/)
    - [hatchet](https://hatchet.run/)
:::

::: {.callout-note appearance="minimal" collapse=true title="Infra 🏗️"} 
- Containers
    - [Docker](https://www.docker.com/)
    - [Kubernetes](https://kubernetes.io/)
- Infrastructure as Code & Config Management
    - [Terraform](https://www.terraform.io/)
    - [Pulumi](https://www.pulumi.com/)
    - [Ansible](https://www.ansible.com/)
- Observability (O11y)
    - [OpenTelemetry](https://opentelemetry.io/)
    - [eBPF](https://ebpf.io/)
    - [Cilium](https://cilium.io/)
    - [DTrace](https://dtrace.org/)
    - [Jaeger](https://www.jaegertracing.io/)
    - [Grafana](https://grafana.com/)
    - [Honeycomb](https://www.honeycomb.io/)
    - [Datadog](https://www.datadoghq.com/)
    - [Sentry](https://sentry.io/welcome/)
:::
