---
title: "Writing Doesn't Have to be Linear"
description: ""
author: "Tyler Hillery"
date: "2026-09-02"
categories: []
filters:
  - social-share
share:
  permalink: "https://tylerhillery.com/blog/writing-doesnt-have-to-be-linear/"
  description:
  twitter: true
  facebook: false
  reddit: true
  stumble: false
  tumblr: false
  linkedin: true
  email: true
  mastodon: true
draft: false 
---

------------------------------------------------------------------------

English was my least favorite subject throughout school. Probably because it was my worst subject. I really struggled with writing (I still do). For a while, I didn’t care to put in the time to get better because I felt Math and Science were much more important.

Then one day I heard someone describe writing as nothing more than thinking, which completely changed my perspective.

The funny part is, I always thought I was a good thinker. My mind loves to think and noodle on topics. The problem was I couldn't communicate these thoughts to others. All these half-baked thoughts in my head were just that, half-baked. Communicating in a way that can be understood by others is how half-baked thoughts become fully baked.

I end up writing most my blog posts because I have these thoughts brewing in my head, and I need to get them out for my sanity. In many ways, writing is therapeutic for me.

When I started taking writing more seriously, I found I struggled the most with [blank page syndrome](https://www.globesoup.net/writing-blog/blank-page-syndrome-how-to-beat-it). This stemmed from me thinking writing always had to be done left to right, introduction to conclusion. Then, in one of my college writing classes, I was introduced to this concept of a "rough rough first draft". This is the draft that only you see. In this draft, you can do whatever you want.

::: {.callout-note }
I tried researching this concept of a "rough rough" first draft and I believe the more common phrase for this type of draft is [Shifty First Drafts](https://wrd.as.uky.edu/sites/default/files/1-Shitty%20First%20Drafts.pdf)
:::

When I write my rough rough first draft,I couldn't care less about writing left to right, introduction to conclusion, or even grammar for that matter. I just write whatever is on my mind. Sometimes I will write the same thing phrased three different ways. I will write one paragraph not knowing where it will end up. In many ways I feel like [Hal](https://youtu.be/EILskqqoHyk?si=pS4hs9tbbAzs-hzM), from Malcolm In The Middle, slapping paint on a canvas just to see what sticks.

When I get done writing everything I read it over. At this point it's much more like fitting puzzle pieces together than it is writing. Now puzzles are something I can get behind. 

So if writing is something you struggled with because you felt it has to be this very linear process, use this as a friendly reminder that it doesn't have to be. Don't be afraid to write that rough rough first draft. If you are still having a hard time writing anything, write about why you're struggling!