---
title: "Math Academy Mathematical Foundations 1"
description: "My notes [Math Academy Mathematical Foundations 1](https://www.mathacademy.com/courses/mathematical-foundations-i)"
author: "Tyler Hillery"
date: "2026-04-08"
filters:
    - social-share
share:
    permalink: "https://tylerhillery.com/notes/math-academy-foundations-1"
    description:
    twitter: true
    facebook: false
    reddit: true
    stumble: false
    tumblr: false
    linkedin: true
    email: true
    mastodon: true
categories: [Courses, In Progress]
---

------------------------------------------------------------------------

# Links
- [Hand Written Notes](https://1drv.ms/p/c/b108287c54af8760/IQAg2mVcOfnuTbeJqLGmofr9AehnUEir94AWCLXhhCS1r-A?e=sRQ6PU)

# Notes 

## Lesson: Points, Lines, Rays, and Segments

- A **line** is a straight object that extends forever in **both** directions
- Using diagrams a **line** is shown with arrows on **both** sides 
- We can represent a line passing through points $S$ and $T$ as $\overleftrightarrow{ST}$
- A **ray** is similar to a line but has a staring point and extends infinitely in one direction only.
- We can represent a ray starting at point $P$ and passing through point $Q$ as $\overrightarrow{ST}$
- A **segment** is part of aline bounded by two points, called **endpoints**.
- We can represent a segment with endpoints $A$ and $B$ as $\overline{AB}$

## Lesson: Additive Inverses of Numbers

- Given a number, its **additive inverse** is the number we need to add to get to zero.

## Lesson: The Greatest Common Factor of Two Linear Expressions

- The **greatest common factor** of two numbers is the largest expression that will divide *both* numbers with no remainder.

## Lesson: Multiplying Mixed Numbers by Whole Numbers

- No notes

## Lesson: Understanding Volume Using Unit Cubes

- **Volume** is the amount of space that an object takes up, measured in **unit cubes**.

## Lesson: Ratio Tables

- No notes

## Lesson: Angles and Measures of Angles

- An **angle** is formed whenever two rays meet at a point.
- The common point shared by the rays is called the **vertex**, and the rays themselves are called **sides** of the angle
- Consider the follow angle made of the following rays $\overrightarrow{AB}$ and $\overrightarrow{AC}$, this can be expressed as $\angle{CAB}$ or $\angle{BAC}$ the vertex is always in the middle. It can also be expressed as $\widehat{CAB}$
- The **measure** of angle is the amount of "turn" from one side of the angle to the other. Angles are measured in **degrees** $^\circ$.

## Lesson: Distance Between Two Points in a Coordinate Plane

- No notes. I am curious though how to calculate the distance when both x,y are different. The problems given were just vertical and horizontal lines.

## Lesson: Solving Problems Using Addition and Subtraction of Rational Numbers

- No notes.

## Lesson: Multiplying Mixed Numbers by Fractions

- No notes.

## Lesson: Sums of Angles

- When two angles share a common side, they are called **adjacent** angles.
- When two angles are adjacent we can add their meseasures to find the larger angle

$$
m\angle{PST} = m\angle{PSR} + m\angle{RST}
$$

## Lesson: Right, Straight, Full, and Null Angles

- Right Angle = $90^\circ$ 
- Straight Angle = $180^\circ$ 
- Null Angle = $0^\circ$ 
- Full Angle = $360^\circ$ 

## Lesson: Decimal and Fraction Operations Applied to Commercial Settings

- No Notes.

## Lesson: Simplifying Linear Expressions When a Group of Terms Is Subtracted

- No Notes.

## Lesson: Splitting Rational Expressions Into Separate Terms

- No Notes.

## Lesson: Simplifying Linear Expressions Containing Fractions

- No Notes.

## Lesson: Multiplying Mixed Numbers

- No Notes.

## Lesson: Acute, Obtuse, and Reflex Angles

- **Acute angle** has a measure between $0^/circ$ and $90^/circ$
- **Obtuse angle** has a measure between $90^/circ$ and $180^/circ$
- **Reflex angle** has a measure between $180^/circ$ and $360^/circ$

## Lesson: Graphing Ratios

- No notes.

## Lesson: Polygons

- A chain of straight lines that form a loop is called a **polygon**
- Line segments are the **sides** for the polygon and the endpoints of the sides are the **vertices**

| Number of Sides | Name          |
|-----------------|---------------|
| 3               | Triangle      |
| 4               | Quadrilateral |
| 5               | Pentagon      |
| 6               | Hexagon       |
| 7               | Heptagon      |
| 8               | Octagon       |
| 9               | Nonagon       |
| 10              | Decagon       |

- Polygon is **simply** if boundary does not intersect otherwise it's **complex**
- Polygon is **convex** if it has no angles pointing inwards otherwise it's **concave**