on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish to Cloudfare Pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write # needed for Cloudflare
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install python dependencies
        run: |
          export UV_PROJECT_ENVIRONMENT="${pythonLocation}"
          uv sync --frozen

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
          
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Latest Wrangler
        run: npm install --global wrangler@4

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}